apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-shop-slos
  namespace: monitoring
  labels:
    component: slo-monitoring
data:
  slos.yaml: |
    # SRE Shop Application - Service Level Objectives
    
    # ==============================================
    # 1. AVAILABILITY SLO
    # ==============================================
    availability_slo:
      name: "SRE Shop Availability"
      description: "Application must be available and responding to requests"
      target: 99.9%  # 99.9% uptime = ~8.77 hours downtime per year
      measurement_window: 30d
      metrics:
        sli_query: "avg_over_time(up{job=\"sre-shop-backend\"}[5m])"
        goal: 0.999
        
    # ==============================================
    # 2. LATENCY SLO  
    # ==============================================
    latency_slo:
      name: "SRE Shop Response Time"
      description: "95% of requests must complete within 200ms"
      target: 95%
      measurement_window: 7d
      metrics:
        # Note: This would need actual latency metrics from application
        sli_query: "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))"
        goal: 0.2  # 200ms in seconds
        
    # ==============================================
    # 3. ERROR RATE SLO
    # ==============================================
    error_rate_slo:
      name: "SRE Shop Error Rate"
      description: "Error rate must be less than 0.1%"
      target: 99.9%  # Success rate (inverse of error rate)
      measurement_window: 7d
      metrics:
        # Based on HTTP status codes and pod restarts
        sli_query: |
          (
            sum(rate(http_requests_total{status!~"5.."}[5m])) /
            sum(rate(http_requests_total[5m]))
          ) or 
          (
            1 - (
              sum(rate(kube_pod_container_status_restarts_total{namespace="sre-shop"}[5m])) /
              sum(kube_pod_info{namespace="sre-shop"})
            )
          )
        goal: 0.999
        
    # ==============================================
    # 4. SATURATION SLO
    # ==============================================
    saturation_slo:
      name: "SRE Shop Resource Utilization"
      description: "Resource utilization should stay below 80%"
      target: 80%
      measurement_window: 1h
      metrics:
        cpu_sli_query: |
          avg(
            rate(container_cpu_usage_seconds_total{namespace="sre-shop"}[5m]) /
            container_spec_cpu_quota{namespace="sre-shop"} * 100
          )
        memory_sli_query: |
          avg(
            container_memory_usage_bytes{namespace="sre-shop"} /
            container_spec_memory_limit_bytes{namespace="sre-shop"} * 100
          )
        goal: 80  # 80% utilization threshold
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-recording-rules
  namespace: monitoring
  labels:
    component: slo-monitoring
data:
  slo-rules.yml: |
    groups:
    - name: sre-shop-slo-recording
      interval: 30s
      rules:
      
      # ============================================
      # AVAILABILITY SLI RECORDING RULES
      # ============================================
      - record: sre_shop:availability_sli:rate5m
        expr: avg_over_time(up{job="sre-shop-backend"}[5m])
        labels:
          slo: "availability"
          service: "sre-shop"
          
      - record: sre_shop:availability_sli:rate1h
        expr: avg_over_time(sre_shop:availability_sli:rate5m[1h])
        labels:
          slo: "availability"
          service: "sre-shop"
          
      - record: sre_shop:availability_sli:rate1d
        expr: avg_over_time(sre_shop:availability_sli:rate5m[1d])
        labels:
          slo: "availability"
          service: "sre-shop"
          
      # ============================================
      # ERROR RATE SLI RECORDING RULES
      # ============================================
      - record: sre_shop:error_rate_sli:rate5m
        expr: |
          1 - (
            sum(rate(kube_pod_container_status_restarts_total{namespace="sre-shop"}[5m])) /
            sum(kube_pod_info{namespace="sre-shop"})
          )
        labels:
          slo: "error_rate"
          service: "sre-shop"
          
      # ============================================
      # SATURATION SLI RECORDING RULES
      # ============================================
      - record: sre_shop:cpu_saturation_sli:rate5m
        expr: |
          avg(
            rate(container_cpu_usage_seconds_total{namespace="sre-shop"}[5m]) * 100
          )
        labels:
          slo: "cpu_saturation"
          service: "sre-shop"
          
      - record: sre_shop:memory_saturation_sli:rate5m
        expr: |
          avg(
            container_memory_usage_bytes{namespace="sre-shop"} / 
            (1024*1024*1024)  # Convert to GB
          )
        labels:
          slo: "memory_saturation"
          service: "sre-shop"
          
      # ============================================
      # SLO COMPLIANCE CALCULATION
      # ============================================
      - record: sre_shop:slo_compliance:availability
        expr: |
          (
            avg_over_time(sre_shop:availability_sli:rate5m[7d]) >= 0.999
          ) * 100
        labels:
          slo: "availability"
          compliance_period: "7d"
          
      - record: sre_shop:slo_compliance:error_rate
        expr: |
          (
            avg_over_time(sre_shop:error_rate_sli:rate5m[7d]) >= 0.999
          ) * 100
        labels:
          slo: "error_rate"
          compliance_period: "7d"