apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: sre-shop
  labels:
    app: backend-api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9898"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: stefanprodan/podinfo:6.5.0
        ports:
        - containerPort: 9898
          name: http
        - containerPort: 9999
          name: grpc
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: sre-shop
  labels:
    app: backend-api
spec:
  selector:
    app: backend-api
  ports:
  - port: 8080
    targetPort: 9898
  type: ClusterIP